version: 2.1
executors:
  default_image:
    docker:
      - image: cimg/base:latest
jobs:
  test:
    executor: default_image
    steps:
    - checkout
workflows:
  Auto Assign:
    jobs:
    - test
