version: 2.1

jobs:
  helloWorld:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo $CIRCLE_PULL_REQUEST
      - run: echo $CIRCLE_REPOSITORY_URL
      - run: echo "This is pipeline ID << pipeline.id >>"
      - run: echo "This is base revision << pipeline.git.base_revision >>"
      - run: echo << pipeline.trigger_parameters.github_app.repo_url >>
      - run: echo $CIRCLE_PR_REPONAME
      - run: echo $CIRCLE_PR_NUMBER
      - run: echo << pipeline.git.commit.author_email >>

workflows:
  helloWorldWorld:
   jobs:
      - helloWorld
