version: 2.1
executors:
  default_image:
    docker:
    - image: cimg/base:current
jobs:
  test:
    executor: default_image
    steps:
    - checkout
    - run:
        command: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust this command according to your
          requirements
          pytest
          
workflows:
  Run Tests:
    jobs:
    - test
