version: 2.1
orbs:
  slack: circleci/slack@4.12.5
  
jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command 
      - run: echo <<pipeline.trigger_parameters.circleci.trigger_type>>
      - run: echo <<pipeline.trigger_parameters.github_app.web_url>>
      - run: echo $CIRCLE_PROJECT_REPONAME
      - run: echo $CIRCLE_BRANCH
      - run: echo $CIRCLE_BUILD_URL
      - slack/notify:
         event: always
         template: basic_fail_1

workflows:
  my-workflow:
    jobs:
      - hello-job # comment
