version: 2.1
jobs:
  unittest:
    environment:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_APP_PEM: ${{ secrets.GH_APP_PEM }}
    docker:
    - image: python:${{ matrix.python-version }}
    steps:
    - checkout
    - run:
        command: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run pytest -n 4 tests/e2e
workflows:
  e2e Tests:
    jobs:
    - unittest:
        filters:
          branches:
            only:
            - main
            - dev
            - testTranslator
