version: 2.1
jobs:
  build:
    docker:
    - image: cimg/openjdk:latest
    - image: circleci/openjdkjdk:latest
    steps:
    - checkout
    - run:
        command: |
          mvn -B package --file pom.xml
workflows:
  Java CI with Maven:
    jobs:
    - build:
        filters:
          branches:
            only:
            - main
            - testTranslator
