version: '2.1'
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.0.0
workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue_config.yml
          mapping: |
            src/.* build-code true .circleci/build-code-config.yml
            doc/.* build-docs true .circleci/build-docs-config.yml

