version: 2.1
orbs: 
  slack: circleci/slack@4.12.5
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to st art using the Windows executor. 
  
jobs:
  hello-job:
    docker: 
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
 #      - image: ubuntu:20.04
    steps:   
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command  
      - run: echo <<pipeline.trigger_parameters.circleci.trigger_type>>
#      - run: echo <<pipeline.trigger_parameters.github_app.web_url>>
      - run: echo $CIRCLE_PROJECT_REPONAME 
      - run: echo $CIRCLE_BRANCH
      - run: echo $CIRCLE_BUILD_URL
      - run: echo <<pipeline.number>>
      - run: echo <<pipeline.trigger_source>>
      - run: echo <<pipeline.id>>
      - run: echo <<pipeline.project.git_url>>
      - run: echo <<pipeline.git.tag>>
      - run: echo <<pipeline.git.branch>>
      - run: echo <<pipeline.trigger_parameters.circleci.event_type>>
      - run: echo <<pipeline.git.revision>>
      - run: echo this is revision <<pipeline.git.revision>>
      - run: echo <<pipeline.git.base_revision>>
 #      - run: echo <<pipeline.trigger_parameters.webhook.body>>
      - run: echo <<pipeline.in_setup>>
      - run: echo <<pipeline.schedule.name>> 
      - run: echo <<pipeline.schedule.id>>
      - run: echo $CIRCLE_PROJECT_USERNAME
      - run: ls .circleci
      - run: 
          name: circle_repository_url
          command: echo $CIRCLE_REPOSITORY_URL
      - run: 
          name: circle_pull_request
          command: echo $CIRCLE_PULL_REQUEST

      - run: 
          name: circle_sha1
          command: echo $CIRCLE_SHA1
      - slack/notify:
         event: always
         template: basic_fail_1
  windows-test: # name of your job
    executor: win/default # executor type
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b7:7d:45:02:91:79:82:48:b0:2a:18:97:85:32:ea:f6"
      - checkout
      - run: Write-Host 'Hello, Windows '
  
  hello2-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - run:
          command: echo 'hello world'

workflows:
  my-workflow:
    jobs:
      - hello-job # comment
      - windows-test
      - hello2-job

