version: 2.1

jobs:
  trivy_security_scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Prerequisites
          command: |
            sudo apt-get update && sudo apt-get install -y curl
      - run:
          name: Install Trivy
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      - run:
          name: Trivy Security Scan
          command: trivy fs .

workflows:
  security_scan_workflow:
    jobs:
      - trivy_security_scan
