version: 2.1
jobs:
  check-circleci-cli:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - run:
          name: Print CircleCI CLI Version
          command: circleci version
workflows:
  version: 2
  build:
    jobs:
      - check-circleci-cli
