version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say Hello"
          command: "echo Hello, World!"
      - run:
          name: "Curl ESPN"
          command: "curl https://www.espn.com"
      - run:
          name: "Curl Yahoo"
          command: "curl https://www.yahoo.com"
  security-scan:
    docker:
      - image: aquasec/trivy:latest
    steps:
      - checkout
      - run:
          name: "Run Trivy Security Scan"
          command: "trivy filesystem --exit-code 1 --severity HIGH,CRITICAL ."

workflows:
  hello-workflow:
    jobs:
      - hello-job
      - security-scan
