version: 2.1

jobs:
  trivy_security_scan:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Trivy
          command: |
            apk --no-cache add curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Trivy Security Scan
          command: trivy fs .

workflows:
  security_scan_workflow:
    jobs:
      - trivy_security_scan
