version: 2.1

jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
    steps:
      - run: echo "hello world"
      - run: sudo -h
      - checkout 
workflows:
  my-workflow:  
      triggers:
        - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - main
    jobs: 
      - build  
