version: '2.1'
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build App
          command: yarn build
workflows:
  version: 2
  build:
    jobs:
      - build
