version: 2.1

dependencies:
  flutter:
    version: 1.0.0

orbs:
  flutter: circleci/flutter@1.0.0

jobs:
  build:
    docker:
      - image: circleci/flutter:latest
    steps:
      - checkout
      - flutter/initialize
      - run: flutter pub get
      - run: flutter build apk

  test:
    docker:
      - image: circleci/flutter:latest
    steps:
      - checkout
      - flutter/initialize
      - run: flutter pub get
      - run: flutter test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
