version: 2.1

jobs:
  scan:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run scan
          command: npm run scan

workflows:
  build-and-scan:
    jobs:
      - scan
