version: 2.1

jobs:
  flutterBuild:
    docker:
      - image: cimg/flutter:3.0.3
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter build apk

  flutterTest:
    docker:
      - image: cimg/flutter:3.0.3
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter test

workflows:
  buildAndTest:
    jobs:
      - flutterBuild
      - flutterTest:
          requires:
            - flutterBuild
