version: 2.1

jobs:
  flutterBuild:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter build apk

  flutterTest:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter test

workflows:
  buildAndTest:
    jobs:
      - flutterBuild
      - flutterTest:
          requires:
            - flutterBuild
