version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: cimg/node:14.18.0-browsers

 steps:
      - browser-tools/install-browser-tools

jobs:
  hello-job:
    docker:
      - image: cimg/node:20.4.0-browsers # the primary container, where your job's commands are run
    steps:
      <<: *defaults
    steps:
      - checkout

workflows:
  my-workflow:
    jobs:
      - hello-job
