version: 2.1 
orbs:
  queue: eddiewebb/queue@3.1.4
  
jobs:
  coverage-linux:
    docker:
     - image: cimg/node:22.0.0

    steps:
      - queue/until_front_of_line:
          job-regex: ^DeployStep[0-9]$
          limit-branch-name: main
          max-wait-time: '10'
          my-pipeline: <<pipeline.number>>
workflows:
  Coverage_Linux:
    jobs:
     - coverage-linux 
