version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  hello-job:
    docker:
      - image: cimg/node:20.4.0-browsers # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - browser-tools/install-browser-tools

workflows:
  my-workflow:
    jobs:
      - hello-job
