version: 2.1
commands:
  set_environment_vars:
    steps:
    - run:
        command: |
          echo "export PYTHON_VERSION=3.12" >> $BASH_ENV
          echo "export FLAKY_TESTS=keep_retrying" >> $BASH_ENV
jobs:
  coverage-linux:
    environment:
      NODE_OPTIONS: --max-old-space-size=8192
    docker:
    - image: cimg/base:2024.05

    steps:
    - checkout
    - set_environment_vars
    - run:
        name: Environment Information
        command: npx envinfo
    - run:
        name: Install gcovr
        command: pip install gcovr==4.2
    - run:
        name: Build
        command: make build-ci -j4 V=1 CONFIG_FLAGS="--error-on-warn --coverage"
    - run:
        name: Test
        command: NODE_V8_COVERAGE=coverage/tmp make test-cov -j4 V=1 TEST_CI_ARGS="-p
          dots --node-args="--test-reporter=spec" --measure-flakiness 9" || exit 0
    - run:
        name: Report JS
        command: npx c8 report --check-coverage
    - run:
        name: Report C++
        command: cd out && gcovr --gcov-exclude=".*\b(deps|usr|out|obj|cctest|embedding)\b"
          -v -r Release/obj.target --xml -o ../coverage/coverage-cxx.xml --root=$(cd
          ../ && pwd)
    - run:
        name: Clean tmp
        command: rm -rf coverage/tmp && rm -rf out
workflows:
  Coverage_Linux:
    jobs:
    - coverage-linux:
        filters:
          branches:
            only:
            - main
          tags: {}
