version: 2.1
commands:
  set_environment_vars:
    steps:
    - run:
        command: |
          echo "export PYTHON_VERSION=3.12" >> $BASH_ENV
          echo "export FLAKY_TESTS=keep_retrying" >> $BASH_ENV
jobs:
  coverage-linux:
    environment:
      NODE_OPTIONS: --max-old-space-size=8192
    docker:
    - image: cimg/node:22.0.0

    steps:
    - checkout
    - run:
        command: sleep 2 min
workflows:
  Coverage_Linux:
    jobs:
    - coverage-linux:
        filters:
          branches:
            only:
            - main
          tags: {}
