version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8


jobs:
  hello-job:
    docker:
      - image: cimg/node:20.4.0-browsers # the primary container, where your job's commands are run
    steps:
      <<: *defaults
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - google-chrome --version

workflows:
  my-workflow:
    jobs:
      - hello-job
